name: pokeball_widget
description: A Pokeball CustomPaint to draw a pokeball.
version: 0.0.1
homepage: https://github.com/deb-95/pokeball_paint

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: